export const LOGOUT = "LOGOUT";
export const UPDATE_CURRENCY = "UPDATE_CURRENCY";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_FEES = "UPDATE_FEES";
export const UPDATE_USER_LANGUAGE = "UPDATE_USER_LANGUAGE";
export const UPDATE_CURRENCY_PRICE = "UPDATE_CURRENCY_PRICE";
export const SET_PROFILE_IMAGE = "SET_PROFILE_IMAGE";










