const Permissions = {

    'ADMIN': ['PRODUCT', 'CATEGORY', 'CAMPAIGN_ADMIN','DONORS','SETTING','DASHBOARD','PROJECT','ORDERS','CMS','PARTNERSHIP','VERIFIED'],
    
    'CAMPAIGN_ADMIN': ['PRODUCT','DASHBOARD','PROFILE','PROJECT']

}
export default Permissions;